blog/urls.py
from django.conf.urls import url
from django.conf import settings
from blog.views import index
from blog.views import tagArticle
from django.views import static

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^uploads/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^tagarticle/.*$', tagArticle, name='tagArticle')
]

blog_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.upload import upload_image


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r'^', include('blog.urls'))
]

blog/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    sex_choices = (
        ('0', '女'),
        ('1', '男'),
        ('2', '未知'),
    )
    marriage_choices = (
        ('0', '未婚'),
        ('1', '已婚'),
        ('2', '离异'),
    )

    occupation_choices = (
        ('0', '士'),
        ('1', '农'),
        ('2', '工'),
        ('3', '商'),
    )

    province_choices = (
        ('0', '北京市'),
        ('1', '天津市'),
        ('2', '上海市'),
        ('3', '重庆市'),
        ('4', '河北省'),
        ('5', '山西省'),
        ('6', '陕西省'),
        ('7', '山东省'),
        ('8', '河南省'),
        ('9', '辽宁省'),
        ('10', '吉林省'),
        ('11', '黑龙江省'),
        ('12', '江苏省'),
        ('13', '浙江省'),
        ('14', '安徽省'),
        ('15', '江西省'),
        ('16', '福建省'),
        ('17', '湖北省'),
        ('19', '湖南省'),
        ('20', '四川省'),
        ('21', '贵州省'),
        ('22', '云南省'),
        ('23', '广东省'),
        ('24', '青海省'),
        ('25', '海南省'),
        ('26', '甘肃省'),
        ('27', '台湾省'),
        ('28', '广西壮族自治区'),
        ('29', '内蒙古自治区'),
        ('30', '新疆维吾尔自治区'),
        ('31', '西藏自治区'),
        ('32', '宁夏回族自治区'),
        ('33', '香港特别行政区'),
        ('34', '澳门特别行政区'),
    )

    city_choices = (
        ('0', '石家庄'),
        ('1', '张家口'),
        ('2', '唐山'),
        ('3', '秦皇岛'),
        ('4', '邯郸'),
        ('5', '邢台'),
        ('6', '保定'),
        ('7', '承德'),
        ('8', '沧州'),
        ('9', '廊坊'),
        ('10', '衡水'),
        ('11', '太原'),
        ('12', '大同'),
        ('13', '阳泉'),
        ('14', '长治'),
        ('15', '晋城'),
        ('16', '朔州'),
        ('17', '晋中'),
        ('18', '运城'),
        ('19', '忻州'),
        ('20', '临汾'),
        ('21', '吕梁'),
        ('22', '呼和浩特'),
        ('23', '包头'),
        ('24', '乌海'),
        ('25', '赤峰'),
        ('26', '通辽'),
        ('27', '鄂尔多斯'),
        ('28', '呼伦贝尔'),
        ('29', '巴彦淖尔'),
        ('30', '乌兰察布'),
        ('31', '兴安'),
        ('32', '锡林郭勒'),
        ('33', '阿拉善'),
        ('34', '南京'),
        ('35', '无锡'),
        ('36', '苏州'),
        ('37', '常州'),
        ('38', '镇江'),
        ('39', '南通'),
        ('40', '泰州'),
        ('41', '扬州'),
        ('42', '盐城'),
        ('43', '淮安'),
        ('44', '宿迁'),
        ('45', '连云港'),
        ('46', '徐州'),
        ('47', '杭州'),
        ('48', '宁波'),
        ('49', '温州'),
        ('50', '嘉兴'),
        ('51', '湖州'),
        ('52', '绍兴'),
        ('53', '金华'),
        ('54', '衢州'),
        ('55', '舟山'),
        ('56', '台州'),
        ('57', '丽水'),
    )

    # name = models.CharField('姓名', max_length=64)
    # email = models.EmailField('邮件', null=True, blank=True)
    # join_date = models.DateTimeField('加入博客时间')

    sex = models.CharField('性别', max_length=1, choices=sex_choices)
    birth = models.DateField('生日', null=True, blank=True)
    mobile = models.CharField('手机', max_length=11, unique=True, null=True, blank=True)
    qq = models.CharField('QQ', max_length=12, unique=True, null=True, blank=True)
    image = models.ImageField('头像', max_length=200, upload_to='image/avatar/%Y/%m/%d',
                              default='image/avatar/default.jpg', null=True, blank=True)
    profile = models.TextField('个人简介', null=True, blank=True)

    marriage = models.CharField('婚姻状况', max_length=1, choices=marriage_choices, null=True, blank=True)
    occupation = models.CharField('职业', max_length=1, choices=occupation_choices, null=True, blank=True)
    home_province = models.CharField('省', max_length=2, choices=province_choices, null=True, blank=True)
    home_city = models.CharField('市', max_length=3, choices=city_choices, null=True, blank=True)

    last_log_in_date = models.DateTimeField('上次登录时间', auto_now=True)

    school = models.CharField('学校', max_length=32, null=True, blank=True)
    profession = models.CharField('专业', max_length=32, null=True, blank=True)
    school_date = models.DateField('入学时间', null=True, blank=True)

    company = models.CharField('公司', max_length=32, null=True, blank=True)
    position = models.CharField('职位', max_length=32, null=True, blank=True)
    work_date = models.DateField('入职时间', null=True, blank=True)

    # collect_articles = models.ManyToManyField(Article, verbose_name='收藏文章')

    def __str__(self):
        return str(self.id) + '(' + self.username + ')'

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']


class ArticleCategory(models.Model):
    category = models.CharField('分类', max_length=10)
    user_id = models.ForeignKey(User, verbose_name='用户ID')

    def __str__(self):
        return self.category

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['id']


class ArticleTag(models.Model):
    tag = models.CharField('标签', max_length=32)

    def __str__(self):
        return self.tag

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']


class Article(models.Model):
    channel_choices = (
        ('0', '新闻'),
        ('1', '体育'),
        ('2', '财经'),
        ('3', '娱乐'),
        ('4', '科技'),
        ('5', '博客'),
        ('6', '图片'),
        ('7', '育儿'),
        ('8', '文史'),
        ('9', '女性'),
    )

    title = models.CharField('题目', max_length=64)
    desc = models.CharField('描述', max_length=128)
    content = models.TextField('内容')
    publish_date = models.DateTimeField('发表时间', auto_now_add=True)
    is_recommend = models.BooleanField('是否推荐', default=False)
    read_count = models.IntegerField('阅读次数', default=0)
    collect_count = models.IntegerField('收藏次数', default=0)
    reprint_count = models.IntegerField('转载', default=0)

    channel = models.CharField('频道', max_length=2, choices=channel_choices, default='4')

    user_id = models.ForeignKey(User, verbose_name='用户')
    category_id = models.ForeignKey(ArticleCategory, verbose_name='分类')
    tag_id = models.ManyToManyField(ArticleTag, verbose_name='标签')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-publish_date']


class ArticleComment(models.Model):
    content = models.CharField('内容', max_length=64)
    publish_date = models.DateTimeField('评论时间', auto_now_add=True)
    article_id = models.ForeignKey(Article, verbose_name='文章ID')
    user_id = models.ForeignKey(User, verbose_name='用户ID')
    p_id = models.ForeignKey('self', null=True, blank=True, verbose_name='父级评论')

    def __str__(self):
        return self.content[:10] + '...'

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-publish_date']


class UserCollectArticle(models.Model):
    user_id = models.ForeignKey(User, verbose_name='用户ID')
    article_id = models.ForeignKey(Article, verbose_name='文章ID')

    def __str__(self):
        return str(self.user_id) + '收藏文章:' + str(self.article_id)

    class Meta:
        verbose_name = '收藏'
        verbose_name_plural = verbose_name
        ordering = ['id']


class UserFans(models.Model):
    user_id = models.ForeignKey(User, verbose_name='用户ID', related_name='userfans_user')
    fans_id = models.ForeignKey(User, verbose_name='粉丝ID', related_name='userfans_fans')

    def __str__(self):
        return str(self.user_id) + '粉丝:' + str(self.fans_id)

    class Meta:
        verbose_name = '粉丝'
        verbose_name_plural = verbose_name
        ordering = ['id']


class UserExt(models.Model):
    user_id = models.ForeignKey(User, verbose_name='用户ID', related_name='userext_user')
    guest_id = models.ForeignKey(User, verbose_name='访客ID', related_name='userext_guest')
    is_message = models.BooleanField('是否留言', default=False)
    message = models.TextField('留言', blank=True)

    def __str__(self):
        if self.is_message:
            return str(self.guest_id) + '留言:' + self.message
        else:
            return str(self.guest_id) + '来访'

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name
        ordering = ['id']


class Ad(models.Model):
    title = models.CharField('标题', max_length=32)
    desc = models.CharField('描述', max_length=64)
    image_url = models.ImageField('图片地址', upload_to='image/ad/%Y/%m/%d', default='image/ad/default.jpg')
    link_url = models.URLField('链接地址')
    publish_date = models.DateTimeField('发表时间', auto_now_add=True)
    click_count = models.IntegerField('点击次数', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '广告'
        verbose_name_plural = verbose_name
        ordering = ['-click_count']


class Link(models.Model):
    title = models.CharField('标题', max_length=32)
    desc = models.CharField('描述', max_length=64)
    link_url = models.CharField('链接地址', max_length=64)
    publish_date = models.DateTimeField('发表时间', auto_now_add=True)
    click_count = models.IntegerField('使用次数', default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['-click_count']

templates/index.html
{% load cache %}
{% load staticfiles %}
<!doctype html>
<html>
<head>

    <title>{{ SITE_NAME }}</title>

    <meta charset="utf-8">
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
    <script src="{% static 'js/modernizr.js' %}"></script>
<![endif]-->
</head>
{% with index='index' %}
{% with body='body' %}
{% cache 500 dashboard index body %}
<body>
<header>
  <div class="logo">
      <h1>{{ SITE_NAME }}</h1>
      <p>{{ SITE_DESC }}</p>
  </div>
  <nav id="topnav" class="f_r">
      <ul>
          <a href="/" target="_blank">首页</a>
          {% for category in category_list %}
              <a href="{{ forloop.counter0 }}" target="_blank">{{ category }}</a>
          {% endfor %}
    </ul>
    <script src="js/nav.js"></script>
  </nav>
</header>

<article>
    <div class="l_box f_l">
        <div class="banner">
            <div id="slide-holder">
                <div id="slide-runner">
                    <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}" alt="" /></a>
                        <div id="slide-controls">
                            <p id="slide-client" class="text"></p>
                                <p id="slide-desc" class="text"></p>
                                    <p id="slide-nav"></p>
                        </div>
                </div>
            </div>
            <script>
                if(!window.slider) {
                    var slider={};
                }

              slider.data= [
                {
                    "id":"slide-img-1", // 与slide-runner中的img标签id对应
                    "client":"标题1",
                    "desc":""           //修改描述
                },
                {
                    "id":"slide-img-2",
                    "client":"标题2",
                    "desc":""
                },
                {
                    "id":"slide-img-3",
                    "client":"标题3",
                    "desc":""
                },
                {
                    "id":"slide-img-4",
                    "client":"标题4",
                    "desc":""
                }
              ];
            </script>
        </div>
        <!-- banner代码 结束 -->


        <div class="topnews">
            <h2>最新文章</h2>
                {% for article in article_list %}
                    <div class="blogs">
                        <ul>
                            <h3>
                                <a href="/">{{ article.title }}</a>
                            </h3>
                            <p>
                                {{ article.desc }}
                            </p>
                            <p class="autor">
                                <span class="lm f_l">
                                    {% for tag in article.tag_id.all %}
                                        <a href="/">{{ tag.tag }} </a>
                                    {% endfor %}
                                </span>
                                <span class="dtime f_l">
                                    {{ article.publish_date | date:'Y-m-d H:i:s' }}
                                </span>
                                <span class="viewnum f_r">
                                    浏览（<a href="/">{{ article.read_count }}</a>）
                                </span>
                                <span class="pingl f_r">
                                    评论（<a href="/">{{ article.articlecomment_set.all.count }}</a>）
                                </span>
                            </p>
                        </ul>
                    </div>
                {% endfor %}
        </div>

        <div id="pagination">
            <ul id="pagination-flickr">
                {% if article_list.has_previous %}
                    <li class="previous"><a href="?page={{ article_list.previous_page_number }}">&laquo;上一页</a></li>
                {% else %}
                    <li class="previous-off">&laquo;上一页</li>
                {% endif %}
                    <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
                 {% if article_list.has_next %}
                     <li class="next"><a href="?page={{ article_list.next_page_number }}">下一页 &raquo;</a></li>
                 {% else %}
                      <li class="next-off">下一页 &raquo;</li>
                  {% endif %}
            </ul>
        </div>
    </div>

    <div class="r_box f_r">
        <div class="tit01">
            <h3>关注我</h3>
                <div class="gzwm">
                    <ul>
                        <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
                        <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
                        <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
                        <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
                    </ul>
                </div>
        </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
        <script>
            window.onload = function ()
            {
                var oLi = document.getElementById("tab").getElementsByTagName("li");
                var oUl = document.getElementById("ms-main").getElementsByTagName("div");
                for(var i = 0; i < oLi.length; i++)
                {
                    oLi[i].index = i;
                    oLi[i].onmouseover = function ()
                    {
                        for(var n = 0; n < oLi.length; n++) oLi[n].className="";
                        this.className = "cur";
                        for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
                        oUl[this.index].style.display = "block"
                    }
                }
            }
        </script>
        <div class="ms-top">
            <ul class="hd" id="tab">
                <li class="cur"><a href="/">浏览排行</a></li>
                <li><a href="/">评论排行</a></li>
                <li><a href="/">站长推荐</a></li>
            </ul>
        </div>
        <div class="ms-main" id="ms-main">
            <div style="display: block;" class="bd bd-news" >
                <ul>
                    {% for read in read_list %}
                        <li><a href="/" target="_blank">{{ read.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div  class="bd bd-news">
                <ul>
                    {% for comment in comment_list %}
                        <li><a href="/" target="_blank">{{ comment.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="bd bd-news">
                <ul>
                    {% for recommend in read_list %}
                        <li><a href="/" target="_blank">{{ recommend.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
        <h3>标签云</h3>
        <ul>
            {% for tag in tag_list %}
                <li><a href="{% url 'tagArticle' %}?tag={{ tag.tag }}">{{ tag.tag }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="tuwen">
        <h3>文章归档</h3>
        <ul>
            {% for article_pub in article_pub_list %}
                {% for art in article_pub %}
                    <li>
                        <p><span class="tutime font-size-18"><a href=''>{{ art  }}</a></span></p>
                    </li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
    <div class="links">
        <h3>友情链接</h3>
        <ul>
            {% for link in link_list %}
                <li><a href="{{ link.link_url }}" target="_blank">{{ link.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    </div>
  <!--r_box end -->
</article>

        <footer>
            <p class="ft-copyright">任凯杰个人博客 ICP备1405040034号</p>
            <div id="tbox">
                <a id="togbook" href="/"></a>
                <a id="gotop" href="#top"></a>
            </div>
        </footer>
    </body>
    {% endcache %}
    {% endwith %}
    {% endwith %}
</html>

templates/tagArticle.html
{% load staticfiles %}
<!doctype html>
<html>
<head>

    <title>{{ SITE_NAME }}</title>

    <meta charset="utf-8">
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sliders.js' %}"></script>
<!--[if lt IE 9]>
    <script src="{% static 'js/modernizr.js' %}"></script>
<![endif]-->
</head>

<body>
<header>
  <div class="logo">
      <h1>{{ SITE_NAME }}</h1>
      <p>{{ SITE_DESC }}</p>
  </div>
  <nav id="topnav" class="f_r">
      <ul>
          <a href="/" target="_blank">首页</a>
          {% for category in category_list %}
              <a href="{{ forloop.counter0 }}" target="_blank">{{ category }}</a>
          {% endfor %}
    </ul>
    <script src="js/nav.js"></script>
  </nav>
</header>

<article>
    <div class="l_box f_l">
        <div class="banner">
            <div id="slide-holder">
                <div id="slide-runner">
                    <a href="/" target="_blank"><img id="slide-img-1" src="{% static 'images/a1.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-2" src="{% static 'images/a2.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-3" src="{% static 'images/a3.jpg' %}" alt="" /></a>
                    <a href="/" target="_blank"><img id="slide-img-4" src="{% static 'images/a4.jpg' %}" alt="" /></a>
                        <div id="slide-controls">
                            <p id="slide-client" class="text"></p>
                                <p id="slide-desc" class="text"></p>
                                    <p id="slide-nav"></p>
                        </div>
                </div>
            </div>
            <script>
                if(!window.slider) {
                    var slider={};
                }

              slider.data= [
                {
                    "id":"slide-img-1", // 与slide-runner中的img标签id对应
                    "client":"标题1",
                    "desc":""           //修改描述
                },
                {
                    "id":"slide-img-2",
                    "client":"标题2",
                    "desc":""
                },
                {
                    "id":"slide-img-3",
                    "client":"标题3",
                    "desc":""
                },
                {
                    "id":"slide-img-4",
                    "client":"标题4",
                    "desc":""
                }
              ];
            </script>
        </div>
        <!-- banner代码 结束 -->


        <div class="topnews">
            <h2>标签文章</h2>
                {% for article in article_list %}
                    <div class="blogs">
                        <ul>
                            <h3>
                                <a href="/">{{ article.title }}</a>
                            </h3>
                            <p>
                                {{ article.desc }}
                            </p>
                            <p class="autor">
                                <span class="lm f_l">
                                    {% for tag in article.tag_id.all %}
                                        <a href="/">{{ tag.tag }} </a>
                                    {% endfor %}
                                </span>
                                <span class="dtime f_l">
                                    {{ article.publish_date | date:'Y-m-d H:i:s' }}
                                </span>
                                <span class="viewnum f_r">
                                    浏览（<a href="/">{{ article.read_count }}</a>）
                                </span>
                                <span class="pingl f_r">
                                    评论（<a href="/">{{ article.articlecomment_set.all.count }}</a>）
                                </span>
                            </p>
                        </ul>
                    </div>
                {% endfor %}
        </div>

        <div id="pagination">
            <ul id="pagination-flickr">
                {% if article_list.has_previous %}
                    <li class="previous"><a href="?page={{ article_list.previous_page_number }}">&laquo;上一页</a></li>
                {% else %}
                    <li class="previous-off">&laquo;上一页</li>
                {% endif %}
                    <li class="active">{{ article_list.number }}/{{ article_list.paginator.num_pages }}</li>
                 {% if article_list.has_next %}
                     <li class="next"><a href="?page={{ article_list.next_page_number }}">下一页 &raquo;</a></li>
                 {% else %}
                      <li class="next-off">下一页 &raquo;</li>
                  {% endif %}
            </ul>
        </div>
    </div>

    <div class="r_box f_r">
        <div class="tit01">
            <h3>关注我</h3>
                <div class="gzwm">
                    <ul>
                        <li><a class="xlwb" href="#" target="_blank">新浪微博</a></li>
                        <li><a class="txwb" href="#" target="_blank">腾讯微博</a></li>
                        <li><a class="rss" href="portal.php?mod=rss" target="_blank">RSS</a></li>
                        <li><a class="wx" href="mailto:admin@admin.com">邮箱</a></li>
                    </ul>
                </div>
        </div>
    <!--tit01 end-->
    <div class="moreSelect" id="lp_right_select">
        <script>
            window.onload = function ()
            {
                var oLi = document.getElementById("tab").getElementsByTagName("li");
                var oUl = document.getElementById("ms-main").getElementsByTagName("div");
                for(var i = 0; i < oLi.length; i++)
                {
                    oLi[i].index = i;
                    oLi[i].onmouseover = function ()
                    {
                        for(var n = 0; n < oLi.length; n++) oLi[n].className="";
                        this.className = "cur";
                        for(var n = 0; n < oUl.length; n++) oUl[n].style.display = "none";
                        oUl[this.index].style.display = "block"
                    }
                }
            }
        </script>
        <div class="ms-top">
            <ul class="hd" id="tab">
                <li class="cur"><a href="/">浏览排行</a></li>
                <li><a href="/">评论排行</a></li>
                <li><a href="/">站长推荐</a></li>
            </ul>
        </div>
        <div class="ms-main" id="ms-main">
            <div style="display: block;" class="bd bd-news" >
                <ul>
                    {% for read in read_list %}
                        <li><a href="/" target="_blank">{{ read.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div  class="bd bd-news">
                <ul>
                    {% for comment in comment_list %}
                        <li><a href="/" target="_blank">{{ comment.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="bd bd-news">
                <ul>
                    {% for recommend in read_list %}
                        <li><a href="/" target="_blank">{{ recommend.title }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!--ms-main end -->
    </div>
    <!--切换卡 moreSelect end -->

    <div class="cloud">
        <h3>标签云</h3>
        <ul>
            {% for tag in tag_list %}
                <li><a href="{% url 'tagArticle' %}?tag={{ tag.tag }}">{{ tag.tag }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="tuwen">
        <h3>文章归档</h3>
        <ul>
            {% for article_pub in article_pub_list %}
                {% for art in article_pub %}
                    <li>
                        <p><span class="tutime font-size-18"><a href=''>{{ art }}</a></span></p>
                    </li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
    <div class="links">
        <h3>友情链接</h3>
        <ul>
            {% for link in link_list %}
                <li><a href="{{ link.link_url }}" target="_blank">{{ link.title }}</a></li>
            {% endfor %}
        </ul>
    </div>
    </div>
  <!--r_box end -->
</article>

        <footer>
            <p class="ft-copyright">任凯杰个人博客 ICP备1405040034号</p>
            <div id="tbox">
                <a id="togbook" href="/"></a>
                <a id="gotop" href="#top"></a>
            </div>
        </footer>
    </body>
</html>